apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: alloydbomni
spec:
  databaseVersion: "16.8.0"
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-mof
    resources:
      cpu: 2
      memory: 8
      disks:
      - name: DataDisk
        size: 10