apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: alloydbomni
  labels:
    app: alloydb
spec:
  databaseVersion: "16.8.0"
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-alloydbomni
    resources:
      cpu: 2
      memory: 8Gi
      disks:
      - name: DataDisk
        size: 10Gi
        storageClass: local-shared
    dbLoadBalancerOptions:
      annotations:
        networking.gke.io/load-balancer-type: "internal"
  allowExternalIncomingTraffic: true
