apiVersion: v1
kind: Service
metadata:
  name: tma-serice
  annotations:
    metallb.io/allow-shared-ip: "vm-runtime-service"
spec:
  selector:
    kubevirt/vm: vm-runtime-01
  externalTrafficPolicy: Local
  loadBalancerIP: 10.215.2.22
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: frontend
  - name: api
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: vm-runstime-ssh
  annotations:
    metallb.io/allow-shared-ip: "vm-runtime-service"
spec:
  selector:
    kubevirt/vm: vm-runtime-01
  type: LoadBalancer
  loadBalancerIP: 10.215.2.22
  ports:
  - protocol: TCP
    name: ssh
    port: 2222
    targetPort: 22