apiVersion: v1
kind: Service
metadata:
  name: vm-runstime-ssh
spec:
  selector:
    kubevirt/vm: vm-runtime-01
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: ssh
    port: 2222
    targetPort: 22
---

apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: vm-runtime-disk-01-boot-dv
  creationTimestamp: null
  annotations:
    vm.cluster.gke.io/storage-access-mode: ReadWriteOnce
spec:
  size: 20Gi
  storageClassName: local-shared
  source:
    http:
      url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
# status:
#   size: "0"
#   virtualMachineAttachments: null
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: vm-runtime-01
  labels:
      vm.cluster.gke.io/predefined-machinetype: "true"
spec:
  osType: Linux #Windows or Linux to enable guestOS features, case sensitive
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 4G
  interfaces:
  - name: eth0
    networkName: pod-network
    default: true
  firmware:
    bootloader:
      type: "uefi"
      enableSecureBoot: true
  disks:
    - boot: true
      driver: virtio
      # readOnly: true
      virtualMachineDiskName: vm-runtime-disk-01-boot-dv
  cloudInit:
    noCloud:
      secretRef:
        name: user-data